models:
  - name: clean_movies
    columns:
      - name: show_id
        tests:
          - unique
          - not_null
      - name: title
        tests:
          - not_null
      - name: director
      - name: actors
      - name: country
      - name: rating
      - name: duration
      - name: listed_in
      - name: description
      - name: release_year
      - name: date_added
  - name: director_summary
    columns:
      - name: director
        tests:
          - not_null
      - name: title_count    
